#!/usr/bin/env python3
"""gen_layout: read npubin.index.json + container header, emit memory map report
and a C header with tensor name constants + expected shapes.

Usage: python gen_layout.py --index <file.index.json> --container <file.npubin>
       --out-header <tensors.h> [--report <layout.txt>]
Checks: every index entry resolves in the container table with matching kind/shape.
"""
import argparse
import json
import struct
import sys

MAGIC = b"NPU1"


def read_table(path):
    with open(path, "rb") as fo:
        data = fo.read(12)
    assert data[:4] == MAGIC, "bad magic"
    ver, n = struct.unpack_from("<II", data, 4)
    assert ver == 0
    with open(path, "rb") as fo:
        data = fo.read()
    p = 12
    entries = {}
    for _ in range(n):
        nl = struct.unpack_from("<H", data, p)[0]
        p += 2
        name = data[p:p + nl].decode()
        p += nl
        kind, od, ind = struct.unpack_from("<BII", data, p)
        p += 9
        doff, blen = struct.unpack_from("<QQ", data, p)
        p += 16
        entries[name] = (kind, od, ind, doff, blen)
    return entries


def c_ident(name):
    return "T_" + "".join(c if (c.isalnum()) else "_" for c in name).upper()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--index", required=True)
    ap.add_argument("--container", required=True)
    ap.add_argument("--out-header", required=True)
    ap.add_argument("--report", default=None)
    args = ap.parse_args()

    idx = json.load(open(args.index))
    tab = read_table(args.container)

    errors = 0
    total = 0
    per_layer_out = {}
    for name, meta in idx.items():
        e = tab.get(name)
        if e is None:
            print(f"MISSING {name}")
            errors += 1
            continue
        kind, od, ind, doff, blen = e
        if kind != meta["kind"]:
            print(f"KIND {name}: index={meta['kind']} container={kind}")
            errors += 1
        total += blen
        parts = name.split(".")
        if "layers" in parts:
            try:
                L = int(parts[parts.index("layers") + 1])
                per_layer_out[L] = per_layer_out.get(L, 0) + blen
            except ValueError:
                pass
    if len(tab) != len(idx):
        print(f"COUNT container={len(tab)} index={len(idx)}")
        errors += 1

    lines = []
    lines.append(f"tensors_index={len(idx)} tensors_container={len(tab)} errors={errors}")
    lines.append(f"payload_bytes={total} payload_gb={total / 1e9:.3f}")
    # weight traffic per decode token: all binary bitplanes + scales (language model)
    lines.append("per_layer_bytes(first 4): " + str({k: per_layer_out[k] for k in sorted(per_layer_out)[:4]}))
    nlayers = len(per_layer_out)
    if nlayers:
        avg = sum(per_layer_out.values()) / nlayers
        lines.append(f"layers={nlayers} avg_layer_bytes={avg:.0f}")
    # KV pools: 16 full-attn layers, 4 heads x 256 dim x 2 (K+V)
    for ctx, tag in ((16384, "16K"), (32768, "32K"), (65536, "65K")):
        for bpv, kname in ((1.0, "Q8"), (0.5, "Q4")):
            kv = 16 * 4 * 256 * 2 * bpv * ctx
            lines.append(f"kv_{tag}_{kname}={kv:.0f}B ({kv / 1e9:.3f}GB)")
    # SSM state: 48 linear layers x 16x128x128 fp32
    ssm = 48 * 16 * 128 * 128 * 4
    lines.append(f"ssm_state={ssm}B ({ssm / 1e6:.1f}MB)")

    hdr = ["#pragma once", "// generated by gen_layout.py - do not edit", ""]
    hdr.append(f"#define BONSAI_NTENSORS {len(idx)}")
    for name, meta in sorted(idx.items()):
        shape = meta["shape"]
        hdr.append(f"// {name} kind={meta['kind']} shape={shape}")
        hdr.append(f"#define {c_ident(name)} \"{name}\"")
    open(args.out_header, "w").write("\n".join(hdr) + "\n")

    report = "\n".join(lines)
    print(report)
    if args.report:
        open(args.report, "w").write(report + "\n")
    if errors:
        sys.exit(1)
    print("LAYOUT OK")


if __name__ == "__main__":
    main()
