#!/usr/bin/env python3
"""gen_ucat: emit ucat.c with UCAT[0x110000] category bits for the C splitter.
bit0 = L (Letter), bit1 = M (Mark), bit2 = N (Number).
Uses the `regex` module Unicode database (same engine family as reference).
"""
import regex

with open(r"D:\Download\Bonsai2_NPU\cdsp\ucat.c", "w") as fo:
    fo.write("// generated by gen_ucat.py - do not edit\n")
    fo.write("const unsigned char UCAT[1114112] = {")
    for cp in range(0x110000):
        ch = chr(cp)
        v = 0
        # surrogate halves are not valid scalar values; leave 0
        if 0xD800 <= cp <= 0xDFFF:
            v = 0
        else:
            if regex.match(r"\p{L}", ch):
                v |= 1
            if regex.match(r"\p{M}", ch):
                v |= 2
            if regex.match(r"\p{N}", ch):
                v |= 4
        fo.write(str(v) + ",")
        if cp % 32 == 31:
            fo.write("\n")
    fo.write("};\n")
print("wrote ucat.c")
